/*
===============================================================================
 CAP-COLLEGE DATABASE
-------------------------------------------------------------------------------
 Version      : 1.0.0
 File         : database/02_users.sql
 Target       : PostgreSQL / Supabase
 Purpose      : Profiles, roles and relationships between users.
 Dependencies : 00_extensions.sql, 01_types.sql, Supabase auth.users
 Idempotent   : Yes
===============================================================================
*/

begin;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  first_name text,
  last_name text,
  display_name text,
  active boolean not null default true,
  locale text not null default 'fr-FR',
  created_at timestamptz not null default statement_timestamp(),
  updated_at timestamptz not null default statement_timestamp(),
  constraint profiles_first_name_length check (
    first_name is null or char_length(first_name) between 1 and 100
  ),
  constraint profiles_last_name_length check (
    last_name is null or char_length(last_name) between 1 and 100
  )
);

create table if not exists public.roles (
  id smallint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  description text,
  system_role boolean not null default true,
  created_at timestamptz not null default statement_timestamp(),
  constraint roles_code_format check (code ~ '^[a-z][a-z0-9_]*$')
);

create table if not exists public.user_roles (
  user_id uuid not null references public.profiles(id) on delete cascade,
  role_id smallint not null references public.roles(id) on delete restrict,
  granted_by uuid references public.profiles(id) on delete set null,
  granted_at timestamptz not null default statement_timestamp(),
  primary key (user_id, role_id)
);

create table if not exists public.guardian_students (
  guardian_id uuid not null references public.profiles(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  relationship_label text,
  created_at timestamptz not null default statement_timestamp(),
  primary key (guardian_id, student_id),
  constraint guardian_students_distinct_users check (guardian_id <> student_id)
);

create index if not exists user_roles_role_id_idx
  on public.user_roles (role_id);

create index if not exists guardian_students_student_id_idx
  on public.guardian_students (student_id);

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin
  insert into public.profiles (
    id,
    first_name,
    last_name,
    display_name
  )
  values (
    new.id,
    nullif(btrim(new.raw_user_meta_data ->> 'first_name'), ''),
    nullif(btrim(new.raw_user_meta_data ->> 'last_name'), ''),
    nullif(btrim(new.raw_user_meta_data ->> 'display_name'), '')
  )
  on conflict (id) do nothing;

  return new;
end;
$function$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

comment on table public.profiles is
  'Application profile linked one-to-one with Supabase auth.users.';
comment on table public.roles is
  'Extensible application roles such as student, guardian and validator.';
comment on table public.user_roles is
  'Many-to-many role assignments; one person may hold several roles.';
comment on table public.guardian_students is
  'Authorized relationships between guardian and student profiles.';
comment on function public.handle_new_auth_user() is
  'Creates the Cap-College profile associated with a new Supabase Auth user.';

commit;
