/*
===============================================================================
 CAP-COLLEGE DATABASE
-------------------------------------------------------------------------------
 Version      : 1.0.0
 File         : database/03_program.sql
 Target       : PostgreSQL / Supabase
 Purpose      : Curriculum hierarchy centered on atomic micro-skills.
 Dependencies : 00_extensions.sql, 01_types.sql, 02_users.sql
 Idempotent   : Yes
===============================================================================
*/

begin;

create table if not exists public.education_cycles (
  id smallint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  sort_order smallint not null,
  active boolean not null default true,
  created_at timestamptz not null default statement_timestamp(),
  constraint education_cycles_sort_order_positive check (sort_order > 0)
);

create table if not exists public.levels (
  id smallint generated by default as identity primary key,
  cycle_id smallint references public.education_cycles(id) on delete restrict,
  code text not null unique,
  name text not null,
  sort_order smallint not null,
  active boolean not null default true,
  created_at timestamptz not null default statement_timestamp(),
  constraint levels_sort_order_positive check (sort_order > 0)
);

create table if not exists public.subjects (
  id smallint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  sort_order smallint not null,
  active boolean not null default true,
  created_at timestamptz not null default statement_timestamp(),
  constraint subjects_sort_order_positive check (sort_order > 0)
);

create table if not exists public.domains (
  id uuid primary key default extensions.gen_random_uuid(),
  subject_id smallint not null references public.subjects(id) on delete restrict,
  code text not null,
  name text not null,
  description text,
  sort_order smallint not null default 1,
  active boolean not null default true,
  created_at timestamptz not null default statement_timestamp(),
  updated_at timestamptz not null default statement_timestamp(),
  unique (subject_id, code),
  constraint domains_sort_order_positive check (sort_order > 0)
);

create table if not exists public.skills (
  id uuid primary key default extensions.gen_random_uuid(),
  domain_id uuid not null references public.domains(id) on delete restrict,
  code text not null,
  name text not null,
  description text,
  sort_order smallint not null default 1,
  active boolean not null default true,
  created_at timestamptz not null default statement_timestamp(),
  updated_at timestamptz not null default statement_timestamp(),
  unique (domain_id, code),
  constraint skills_sort_order_positive check (sort_order > 0)
);

create table if not exists public.micro_skills (
  id uuid primary key default extensions.gen_random_uuid(),
  skill_id uuid not null references public.skills(id) on delete restrict,
  code text not null unique,
  teacher_name text not null,
  student_name text not null,
  description text,
  lesson_reminder text,
  worked_example text,
  mastery_criteria text,
  sort_order smallint not null default 1,
  active boolean not null default true,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default statement_timestamp(),
  updated_at timestamptz not null default statement_timestamp(),
  constraint micro_skills_sort_order_positive check (sort_order > 0),
  constraint micro_skills_atomic_names_nonempty check (
    btrim(teacher_name) <> '' and btrim(student_name) <> ''
  )
);

create table if not exists public.micro_skill_levels (
  micro_skill_id uuid not null
    references public.micro_skills(id) on delete cascade,
  level_id smallint not null references public.levels(id) on delete cascade,
  is_expected boolean not null default true,
  primary key (micro_skill_id, level_id)
);

create table if not exists public.micro_skill_prerequisites (
  micro_skill_id uuid not null
    references public.micro_skills(id) on delete cascade,
  prerequisite_micro_skill_id uuid not null
    references public.micro_skills(id) on delete restrict,
  required boolean not null default true,
  primary key (micro_skill_id, prerequisite_micro_skill_id),
  constraint micro_skill_prerequisites_no_self_reference check (
    micro_skill_id <> prerequisite_micro_skill_id
  )
);

create index if not exists domains_subject_id_idx
  on public.domains (subject_id, sort_order);
create index if not exists skills_domain_id_idx
  on public.skills (domain_id, sort_order);
create index if not exists micro_skills_skill_id_idx
  on public.micro_skills (skill_id, sort_order);
create index if not exists micro_skill_levels_level_id_idx
  on public.micro_skill_levels (level_id);
create index if not exists micro_skill_prerequisites_prerequisite_idx
  on public.micro_skill_prerequisites (prerequisite_micro_skill_id);

drop trigger if exists set_domains_updated_at on public.domains;
create trigger set_domains_updated_at
before update on public.domains
for each row execute function public.set_updated_at();

drop trigger if exists set_skills_updated_at on public.skills;
create trigger set_skills_updated_at
before update on public.skills
for each row execute function public.set_updated_at();

drop trigger if exists set_micro_skills_updated_at on public.micro_skills;
create trigger set_micro_skills_updated_at
before update on public.micro_skills
for each row execute function public.set_updated_at();

comment on table public.micro_skills is
  'Atomic learning objectives: one rule, one example and one automatism.';
comment on table public.micro_skill_levels is
  'Levels at which a micro-skill belongs to the expected curriculum.';
comment on table public.micro_skill_prerequisites is
  'Directed prerequisite links used to build progressive learning paths.';

commit;
