/*
===============================================================================
 CAP-COLLEGE DATABASE
-------------------------------------------------------------------------------
 Version      : 1.0.0
 File         : database/05_learning.sql
 Purpose      : Mastery tracking and micro-skill remediation sessions.
 Dependencies : 00_extensions.sql through 04_questions.sql
 Idempotent   : Yes
===============================================================================
*/

begin;

create table if not exists public.student_micro_skill_mastery (
  student_id uuid not null references public.profiles(id) on delete cascade,
  micro_skill_id uuid not null
    references public.micro_skills(id) on delete cascade,
  status public.mastery_status not null default 'not_assessed',
  mastery_score public.percentage_score,
  confidence_score public.percentage_score,
  evidence_count integer not null default 0,
  last_assessed_at timestamptz,
  next_review_at timestamptz,
  updated_at timestamptz not null default statement_timestamp(),
  primary key (student_id, micro_skill_id),
  constraint mastery_evidence_count_nonnegative check (evidence_count >= 0)
);

create table if not exists public.mastery_history (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  micro_skill_id uuid not null
    references public.micro_skills(id) on delete cascade,
  status public.mastery_status not null,
  mastery_score public.percentage_score,
  confidence_score public.percentage_score,
  evidence_count integer not null,
  recorded_at timestamptz not null default statement_timestamp(),
  source text not null,
  constraint mastery_history_evidence_nonnegative check (evidence_count >= 0),
  constraint mastery_history_source check (
    source in ('diagnostic', 'remediation', 'manual', 'recalculation')
  )
);

create table if not exists public.learning_resources (
  id uuid primary key default extensions.gen_random_uuid(),
  micro_skill_id uuid not null
    references public.micro_skills(id) on delete cascade,
  title text not null,
  reminder text not null,
  worked_example text not null,
  version_number integer not null default 1,
  active boolean not null default true,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default statement_timestamp(),
  updated_at timestamptz not null default statement_timestamp(),
  unique (micro_skill_id, version_number),
  constraint learning_resources_version_positive check (version_number > 0)
);

create table if not exists public.remediation_sessions (
  id uuid primary key default extensions.gen_random_uuid(),
  student_id uuid not null references public.profiles(id) on delete cascade,
  micro_skill_id uuid not null
    references public.micro_skills(id) on delete restrict,
  resource_id uuid references public.learning_resources(id) on delete set null,
  planned_minutes smallint,
  status public.learning_session_status not null default 'active',
  started_at timestamptz not null default statement_timestamp(),
  completed_at timestamptz,
  constraint remediation_sessions_planned_minutes check (
    planned_minutes is null or planned_minutes between 1 and 180
  ),
  constraint remediation_sessions_dates check (
    completed_at is null or completed_at >= started_at
  )
);

create table if not exists public.remediation_attempts (
  id bigint generated by default as identity primary key,
  remediation_session_id uuid not null
    references public.remediation_sessions(id) on delete cascade,
  question_id uuid not null references public.questions(id) on delete restrict,
  question_version_id uuid not null
    references public.question_versions(id) on delete restrict,
  selected_choice_id uuid references public.answer_choices(id) on delete restrict,
  assistance public.assistance_mode not null,
  is_correct boolean,
  sequence_number integer not null,
  answered_at timestamptz,
  unique (remediation_session_id, sequence_number),
  constraint remediation_attempts_sequence_positive check (sequence_number > 0)
);

create index if not exists mastery_micro_skill_idx
  on public.student_micro_skill_mastery (micro_skill_id, status);
create index if not exists mastery_history_student_idx
  on public.mastery_history (student_id, recorded_at desc);
create index if not exists remediation_sessions_student_idx
  on public.remediation_sessions (student_id, started_at desc);

drop trigger if exists set_student_mastery_updated_at
  on public.student_micro_skill_mastery;
create trigger set_student_mastery_updated_at
before update on public.student_micro_skill_mastery
for each row execute function public.set_updated_at();

drop trigger if exists set_learning_resources_updated_at
  on public.learning_resources;
create trigger set_learning_resources_updated_at
before update on public.learning_resources
for each row execute function public.set_updated_at();

comment on table public.student_micro_skill_mastery is
  'Current competency-centered estimate built gradually across sessions.';
comment on table public.remediation_attempts is
  'Practice evidence with the course reminder visible or hidden; speed is not scored.';

commit;
