/*
===============================================================================
 CAP-COLLEGE DATABASE
-------------------------------------------------------------------------------
 Version      : 1.0.0
 File         : database/06_diagnostics.sql
 Purpose      : Progressive, time-boxed diagnostic sessions and answers.
 Dependencies : 00_extensions.sql through 05_learning.sql
 Idempotent   : Yes
===============================================================================

 The chosen duration organizes the session only. Response speed is deliberately
 not stored as evidence and never affects mastery.
*/

begin;

create table if not exists public.diagnostics (
  id uuid primary key default extensions.gen_random_uuid(),
  student_id uuid not null references public.profiles(id) on delete cascade,
  subject_id smallint not null references public.subjects(id) on delete restrict,
  level_id smallint not null references public.levels(id) on delete restrict,
  status public.diagnostic_status not null default 'active',
  started_at timestamptz not null default statement_timestamp(),
  completed_at timestamptz,
  updated_at timestamptz not null default statement_timestamp(),
  constraint diagnostics_dates check (
    completed_at is null or completed_at >= started_at
  )
);

create table if not exists public.diagnostic_sessions (
  id uuid primary key default extensions.gen_random_uuid(),
  diagnostic_id uuid not null
    references public.diagnostics(id) on delete cascade,
  planned_minutes smallint not null,
  status public.session_status not null default 'active',
  started_at timestamptz not null default statement_timestamp(),
  ended_at timestamptz,
  constraint diagnostic_sessions_planned_minutes check (
    planned_minutes between 1 and 180
  ),
  constraint diagnostic_sessions_dates check (
    ended_at is null or ended_at >= started_at
  )
);

create table if not exists public.diagnostic_items (
  id bigint generated by default as identity primary key,
  session_id uuid not null
    references public.diagnostic_sessions(id) on delete cascade,
  question_id uuid not null references public.questions(id) on delete restrict,
  question_version_id uuid not null
    references public.question_versions(id) on delete restrict,
  selected_choice_id uuid references public.answer_choices(id) on delete restrict,
  sequence_number integer not null,
  is_correct boolean,
  presented_at timestamptz not null default statement_timestamp(),
  answered_at timestamptz,
  unique (session_id, sequence_number),
  constraint diagnostic_items_sequence_positive check (sequence_number > 0),
  constraint diagnostic_items_answer_consistency check (
    (answered_at is null and selected_choice_id is null and is_correct is null)
    or answered_at is not null
  )
);

create index if not exists diagnostics_student_idx
  on public.diagnostics (student_id, started_at desc);
create index if not exists diagnostic_sessions_diagnostic_idx
  on public.diagnostic_sessions (diagnostic_id, started_at);
create index if not exists diagnostic_items_question_idx
  on public.diagnostic_items (question_id);

drop trigger if exists set_diagnostics_updated_at on public.diagnostics;
create trigger set_diagnostics_updated_at
before update on public.diagnostics
for each row execute function public.set_updated_at();

comment on table public.diagnostics is
  'Long-lived diagnostic that progressively maps a student’s competencies.';
comment on table public.diagnostic_sessions is
  'A calm session organized by a chosen duration, with pause and later continuation.';
comment on table public.diagnostic_items is
  'Immutable evidence for reviewing the student answer and correction after a session.';

commit;
